baseURL = 'https://www.enauara.dev.br'
languageCode = 'pt-br'
title = 'Enauara Badin'
theme = 'beautifulhugo'

#[Params]
#    author = "Enauara Badin."
#    description = "Descricao teste"
#    googleAnalytics = "G-K71X1MC0KG"
